baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

# 相対パスで出力
relativeURLs = true

# 未来の日付の記事も公開する
buildFuture = true

# 要約の単語数（デフォルトは70）
summaryLength = 30

[params]
  mainSections = ['tutorials']      # 表示するセクション
  recent_posts_number = 5       # プレビュー付き記事数（デフォルト3）

[pagination]
  pagerSize = 3    # 1ページあたりの記事数